baseURL = "https://jimthecactus.github.io/nanowrimo_2025/"
title = "NaNoWriMo 2025"
languageCode = "en-us"

[params]
primaryColor = "#00ff7f"
backgroundColor = "#001a00"
maxContentWidth = "800px"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  chapters = "/chapters/:slug/"

[page]
  nextPrevInSectionSortOrder = 'asc'
  nextPrevSortOrder = 'asc'


